project_id = "uwgcqfzzaukonhxkrbtv"

[functions.process-photos]
verify_jwt = false

[functions.linkedin-auth]
verify_jwt = false

[functions.linkedin-post]
verify_jwt = false

[functions.regenerate-layout]
verify_jwt = false
